### ISSUE TITLE
Problem when having multiple instances of richtext editors in one page.

### ISSUE THREAD

**Issue by Bluecoaster455** [webfashionist/RichText#10]
Hello.

I am currently using your richtext editor and tried to put more than one <textarea> in my HTML with a class to instantiate the plugin. 

This happens:
https://imgur.com/a/fMf6j

With that, when I enter html edit mode, every other instances in the page are being changed into html edit mode.

Any clue how to fix it? Or is it a bug?

Thanks!

**Comment by webfashionist** [comment]
It seems as well that the top editor toolbar is missing in the editors following the first one.

Usually, it should block the toolbar buttons of the other editors, but they shouldn't as well switch into the HTML mode. You can check the live preview for the multiple editors (which is available in the examples directory in this repository as well) here: https://htmlpreview.github.io/?https://github.com/webfashionist/RichText/blob/master/examples/multipleEditors.html 

If your issue does still occur after having compared your code to the example in this repository, please append the code where you call the plugin to your next reply here.

**Comment by Bluecoaster455** [comment]
Okay I've tried to modify my code with the help of the example and it worked. 

It seems like each editors need to be called seperatly with a different selector. What I've done is assign the same class for all my editors and call $(".texteditor").richText() once, which works for most of the widgets using jquery. This one seem to have failed so I changed it like the example and works.

Is there any ways for future updates to allow calling .richText() once in a page for all editors?

**Comment by webfashionist** [comment]
Yes, currently each editor needs a different selector. 

Such an update isn't planned currently as the editor is implemented in a separate closed-source CMS tool which needs a bit more attention currently. However, it might be implemented in the future.

**Comment by Bluecoaster455** [comment]
Alright thanks for the help! Love this editor!
