### ISSUE TITLE
Adding languages versions

### ISSUE THREAD

**Issue by Phantomrider** [webfashionist/RichText#11]
Hi, I am using your amazing plugin, but I have a little problem - every time I update the core files my translations (the project is for non-English speakers) for the plugin are gone, which is a bummer, because I have to translate it again, then minify it and upload it to my project.
It would be nice if you can add an array option (or maybe getting langs from stand-alone file) for specific language. This would be great, because it would allow us to use your plugin for multilingual websites.

**Comment by webfashionist** [comment]
Hi,

Thank you for your feedback.

I will implement this as soon as possible.

**Comment by webfashionist** [comment]
I've added a translation object, where you can change the texts. Keep in mind, that the keys of the object should not change.

I didn't want to read the languages from standalone files, as the performance of the editor would decrease. 

I hope this helps :)

**Comment by Phantomrider** [comment]
Thank you very much! Just a side note - you missed one translation - of the buttons to confirm and close dialogs! :)
Btw, it would be nice if the translations object could be used as a title attribute for the toggle buttons. But it's not something you can't live without. Thanks again!

**Comment by webfashionist** [comment]
Which button do you mean? The blue button which adds the data from the dialog to the editor?
I've translated that one with `translations.add`.

Title attributes will be added at some point, but usually they are the same through every editor and office tool, so everyone should know how they react :)

**Comment by Phantomrider** [comment]
Opps, my bad about the button, sorry... About title attribute - I suggested it, mainly because of the formatting trimmer icon. I got a feedback that it was a little bit confusing if you did not use it.
Well, it can always be changed, since the plugin is using FontAwesome. :)

**Comment by webfashionist** [comment]
There were still a few translations missing: I forgot the error messages
I had a bit time left and added title attributes at the same time, now it should be more clear.

I hope this helps :)

I won't create a new release right now for that last update, so if you are downloading from there, please use the Download/Clone button on the main repository page instead for now

**Comment by Phantomrider** [comment]
Perfect, thank you again!
