### ISSUE TITLE
Type some text and press Enter to move to a new line is not working

### ISSUE THREAD

**Issue by tasosstr** [webfashionist/RichText#113]
Hello, 

Thank you very much for the very nice plug in.

For some unknown reason if i will load data, when opening the form, then when i type some text and press Enter to move to a new line is not working at all.

The load data i do it with 
 $('.richText-editor').trigger('setContent','<div>Some text here for test ...</div>');

any help please ?

Thank you in advance.

**Comment by webfashionist** [comment]
Hi @tasosstr 

thank you for your question.

Are you using `\n` for new lines? If so, the code should look like this:

```js
$('.richText-editor').trigger('setContent','\n\nSome text here for test ...\n');
```

Can you check if this works for you?

**Comment by tasosstr** [comment]
Hello dear friend, 

Thank you very much for the reply ! ! !

I try you're test code and it gives me all string in one line (no brake ) 
![image](https://github.com/webfashionist/RichText/assets/20454403/144a0fba-324f-4b0f-b2f8-707cddfa7020)
but here looks it does 
![image](https://github.com/webfashionist/RichText/assets/20454403/5a9602de-5331-45a4-9141-9f4a091ee22e)

then you give the idea and i try the 
$('.richText-editor').trigger('setContent','<br>Some text here for test ...<br>Some text here for test ...<br>');

![image](https://github.com/webfashionist/RichText/assets/20454403/fc7e2ea8-9f69-490f-99a2-da62a4686d77)
and with html code button looks like 
![image](https://github.com/webfashionist/RichText/assets/20454403/bf66060f-f99b-401b-ad4e-fe5750bae13e)

Now the problem when i fetch the data (it is stored from other text properly, i do a migration from other development) is not allow me to press enter to go to the new line and write, only allow me to write in the same line.

I was try to write 
$('.richText-editor').trigger('setContent',information).replace("\n", "<br>").replace("\r", "<br>").replace("\r\n", "<br>");
but no luck  
![image](https://github.com/webfashionist/RichText/assets/20454403/8e399512-902d-4576-9808-45d74a38dc15)

And this is what i got when i press button 'show HTML code'
![image](https://github.com/webfashionist/RichText/assets/20454403/16a17521-e6fd-49d2-85d7-86fcd4ff8b98)


  Thank you very much :-)

**Comment by tasosstr** [comment]
Hello dear friend,

The problem was in another place (I use for some reason that I do not remember) block on char 13 on the form I was trying to retrieve data. I removed it, and now everything is working now as should be

The only is not working for some reason is 
     $('#comment_get').trigger('getContent', function (event, content) {
         console.log(content);
    });

**Comment by webfashionist** [comment]
Hi @tasosstr

Glad that you found the issue.

What exactly is not working with `getContent`?

**Comment by tasosstr** [comment]
Hellpo Dear friend,

Thank you very much for the reply :-)

If i have understand well, when i type something should i get the result in console log ?

i try also 
  $('.richText-editor').trigger('getContent', function (event, content) {
        console.log(content);
    });

and with this on load i got

undefined

And when i type no  other event i have :-)
