### ISSUE TITLE
Malformed conditional is setting cursor on unrelated images.

### ISSUE THREAD

**Issue by michaelthornberry** [webfashionist/RichText#123]
### Describe the problem

Line 1027, there is a check as such:

`if ($target.prop("tagName") === "IMG" && $target.parents("#" + editorID)) {`

Since `$target.parents("#" + editorID)` returns a valid jQuery result, the following code is executed even though the .length of that query may be 0.

### What did you expect?

The conditional should check the length of the result:

`if ($target.prop("tagName") === "IMG" && $target.parents("#" + editorID).length) {`

### What version and browser are you using?

Version: 1.1.0
Browser and version: Chrome 126.0.6478.114

### Bug report checklist

- [x ] I have filled out as much of the above information as I can
- [ ] I have included a test case because my odds go _way_ up that the issue can be fixed when I do
- [ x] I have [searched for existing issues](https://github.com/webfashionist/RichText/issues) and to the best of my knowledge this is not a duplicate

**Comment by webfashionist** [comment]
Hi @michaelthornberry 

thank you for your report! The issue has been fixed with [ed1c663](https://github.com/webfashionist/RichText/commit/ed1c6631ed6b1b893271cf75aa812bdd7cc951a9)

**Comment by michaelthornberry** [comment]
> thank you for your report! The issue has been fixed with [ed1c663]

Thanks!
