### ISSUE TITLE
Getting error when attaching image

### ISSUE THREAD

**Issue by RavishaHesh** [webfashionist/RichText#13]
I'm getting an error when attaching error(Cannot read property 'editorID' of undefined). I checked the demo and it also has this issue
![screen shot 2018-02-08 at 3 30 57 pm](https://user-images.githubusercontent.com/6573956/35966865-1a72b654-0ce5-11e8-9e39-591b4533851e.png)

**Comment by webfashionist** [comment]
How did you attach the image? 
Using the button "Add image" and entering any image path works fine for me

**Comment by RavishaHesh** [comment]
Sorry for the late reply, I just tried it on firefox also and it gave me a different error message.

Error message on firefox
![capture](https://user-images.githubusercontent.com/6573956/35984514-9b9ffefa-0d1a-11e8-8465-8f29b6512153.PNG)

Chrome
![ezgif-4-af59772526](https://user-images.githubusercontent.com/6573956/35984516-9bde1d48-0d1a-11e8-91ed-36fa9544a4e0.gif)

Firefox
![ezgif-4-dfe52eec60](https://user-images.githubusercontent.com/6573956/35984518-9c13cbaa-0d1a-11e8-9ea5-63d441101983.gif)

**Comment by webfashionist** [comment]
Quick workaround: Click in the editor field (where the image should be added) before adding the image.

I'll fix this issue in the code asap, so that the workaround won't be needed anymore.

**Comment by webfashionist** [comment]
Thank you for your feedback!
I've added a fix for the use case you showed in the GIFs. Hope this helps :)
