### ISSUE TITLE
toggleCode is not defined when calling function from another script?

### ISSUE THREAD

**Issue by ZonkedCompanion** [webfashionist/RichText#14]
I might be going about this entirely the wrong way and I'm not sure if this is an actual issue with RichText itself, but if I try and call toggleCode() I get "Uncaught ReferenceError: toggleCode is not defined".

Basically I was trying to toggle "code mode" from another script on the same page by calling this function. For now I have made it work in a hacky kind of way by effectively copying the contents of the original toggleCode() function and creating my own function which I can then call.

Is there an easier and more elegant way to toggle code mode from another script?

**Comment by webfashionist** [comment]
The function `toggleCode()` is only available inside the scope of the jQuery plugin itself.
If you need to call it outside of the plugin, you might just copy it as you already did

**Comment by ZonkedCompanion** [comment]
Hmm ok I thought that might be the case. Thanks for your swift response. Do you think you will ever add an option to start the editor in code mode by default? That would be really useful (for myself at least) Say for example...
`
$(element).richText({       
     defaultView: code
});
`

**Comment by ZonkedCompanion** [comment]
Actually you probably wouldn't need to add that as an option. This one liner seems to be reliable.

`
$(element).richText();
$('*[data-command="toggleCode"]').trigger('click');
`

Thanks for your time and keep up the good work :)
