### ISSUE TITLE
Feature request: NPM Package

### ISSUE THREAD

**Issue by bit-mschwingenschloegl** [webfashionist/RichText#146]
### Describe the problem you'd like to see solved or additional feature for RichText

Are there any plans to create a NPM package of your project?

I have to create SBOMs (Software Bill of Materials) which include all used libraries. Using any package manager (as NPM or yarn) would allow me to generate the required file automatically during build pipeline. (e.g. by using [CycloneDX](https://github.com/CycloneDX))

The only package I found seems to be unofficial: https://www.npmjs.com/package/richtext_for_npm

### Is there an existing part of RichText this feature is related to or is it something new?

This should only affect the deployment pipeline 

### Why would other RichText users care about this?

SBOMs (Software Bill of Materials) are required for any software in europe by the CRA (Cyber Resilience Act) till 2027.

See also: https://digital-strategy.ec.europa.eu/en/policies/cyber-resilience-act

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend this feature to be done?

8 - It would be great if the topic could be realized by march.

### Feature request checklist

- [X] This is a single feature (i.e. not a re-write of all of RichText)
- [X] The title starts with "Feature request: " and is followed by a clear feature name (e.g.: `Feature request: moar cowbell`)
- [X] I have [searched for existing issues](https://github.com/webfashionist/RichText/issues) and to the best of my knowledge this is not a duplicate

**Comment by webfashionist** [comment]
Hi @bit-mschwingenschloegl 

thank you for your request. I've now published RichText to npm and added an automated publish workflow on release just to be sure to have it up-to-date as soon as a new release is added here on Github.

Hope it helps.

https://www.npmjs.com/package/@webfashionist/richtext

**Comment by bit-mschwingenschloegl** [comment]
Thank you very much. This makes it a lot easier for me.

I wish you a merry Christmas and a happy new year.
