### ISSUE TITLE
Textarea change event?

### ISSUE THREAD

**Issue by jerearaujo03** [webfashionist/RichText#18]
How can I detect a change in the content of textarea? May be text input or html generated by the editor.

**Comment by webfashionist** [comment]
You will need to listen for the `keyup` event to be triggered.

Either binded to the `textarea`:

```javascript
$('.richText textarea').on('keyup', function() {
    console.log($(this).val());
});
```
or to the formatted HTML code (WYSIWYG view):
```javascript
$('.richText-editor').on('keyup', function() {
    console.log($(this).html());
});
```

You probably want to use both event listeners, if you want to check for any changes made in both views.
Other events do work as well, like for example `paste`.
