### ISSUE TITLE
Change the height of the editorframe

### ISSUE THREAD

**Issue by Pruus** [webfashionist/RichText#2]
I cannot change the height fo the editing frame. It persists the same. The 400 stays 400.

**Comment by webfashionist** [comment]
The CSS selector for the editor is `.richText .richText-editor`. It is set to a height of 300px by default. 
The code editor has the CSS selector `.richText .richText-initial` and has a `min-height` and `height` set to 400px. 

If you want to change this, change the height with the same selectors. It could as well be possible that you may need the `!important` flag in your CSS value, depending on how you implement your CSS.

It could be possible, that I add the height to the plugin options as well anytime soon.

**Comment by Pruus** [comment]
Great message!

Ik like the editor. Perhaps for my next project.

Thanks for the fast reply. Your the best!

Met vriendelijke groet,

Oldbergh b.v.
Jan te Pas

T: +31 314 33 59 49
M:+31 6 31 78 71 06
E: info@oldbergh.nl

Asterstraat 104
Doetinchem 7004 DS
Nederland

**Comment by webfashionist** [comment]
Thank you for your positive feedback!

I've already added the option to the plugin itself with the latest commit bb1b2f6. 
It is now possible to set the `height` option. If you keep the option to the default value of `0`, it uses the CSS settings from `richtext.min.css`, if the value is bigger than `0` it sets the new custom height directly for the editor frame and code view.

_This update is not yet in the [releases](https://github.com/webfashionist/RichText/releases) list, if you need to download it, please do so by downloading it using the `Clone or download` button on the repository page._

If you want to know more about the available options and their default values, please see the [README](https://github.com/webfashionist/RichText#options) file.

**Comment by Pruus** [comment]
Hi Bob,

What a speed in changing things. I’m very happy with it an gone test it.

THANKS!!!!!!

regards,

JAN

**Comment by Pruus** [comment]
Hi Bob,

i saw a flaw. If you open the mulptiple demo. And open on both the ? then the infoscreen can’t closed.

just a detail, and only in multiple use.

Regards,

Jan

**Comment by webfashionist** [comment]
Thank you for pointing that issue out!

The bug with the info popup should now be fixed with 1949bcc.


_This update is not yet in the releases list, if you need to download it, please do so by downloading it using the `Clone or download` button on the repository page._

**Comment by Pruus** [comment]
Hi Bob,


Very good. May i stretch the edge just a littlebit, sort of?

The new code works like a charm. Great to change the height. I love it. I have tested a few things and for now i’m very happy. But could you stretch the edge?

I had change the value in 80% because i did not wan't the whole screen so i would like to use the ‘%’ for height. I know, i know. I ask to much…. But…But…But..


Keep up doing a great job and many thanks.

Groeten van Jan

**Comment by webfashionist** [comment]
I've added the percentage heights as well with 02c0b00, however the option is called `heightPercentage` to split it into two functionalities.
Simply add `heightPercentage: 80` as option to get 80% of the height. 

This (currently) only works if the parent element of the editor has a fixed height, as the editor frame is only one of a few child elements of the actual editor container. The editor frame therefore gets the height in pixels based from the percentage and parent height given.

I hope this will work fine for you.

**Comment by Pruus** [comment]
You”re fast. great. I’ll test it. Thanks.

**Comment by Pruus** [comment]
Hi Bob,
I've tested this. And it works allmost perfect..... Indeed, the measurement is the insite the standard frame and that is 400 pixels. What i would like to use is that 100(%) takes the whole/full screenheight. So measure what screenheight is possible for that device. That is 100(%). And now i can scale right down to 80% or 70%. The current implecation is that the heightPercentage takes the height of 400px and than calculate a percentage of it. Is it possible to go out of the standard?  This gives a more an gentle better experience. If not... I am glad with the possibility to set the height in pixels. Again Thanks Bob!
groet
Jan

**Comment by webfashionist** [comment]
It currently takes the height of the parent element of the editor, calculates the percentage, removes paddings, margins of the editor and the height of the toolbar and the final result is the new size for the editor. So it does take the parent child of the editor into consideration for the height.

Another way is currently not possible to implement, sorry.

**Comment by Pruus** [comment]
thanks for the reply. I know your outline, but i was trying to stretch the edge. My thinking was that when you call the editing box, the current height of the screen is taken. And than the measurement in percentage while use that percentage of window.innerWidth; The user have to take care of all extra's. That was my thought. But i like your Editor. Thanks!

A last question, is it possible to set those variables in the page code and not in the css. Just a thought. Regards and greetings.

**Comment by webfashionist** [comment]
I don't really understand, why you'd want to use the height of the screen instead of the height of the parent container. The reason is, that probably most devs will implement the editor in an existing CMS and not use it in a fullscreen view. 

And what do you mean by setting the variables to the page code instead of the CSS? You can of course use CSS with the `<style>` tags to change the layout and design of the editor.

**Comment by Pruus** [comment]
Hi Bob,

I was just thinking about the possibility that the editor can be used on a seperat window. So thats the reason for asking. I’m very content en pleased with your solution. Only thought that it could be broader used.

I was thinking of using two differen editor on one page. So changing the hight cq precentage is global and can’t be changed per editor. So when i could change the parameters height and percentage outside the .js, that would give the possibility to do it. That’s the reasen for the question.  

Please keep u doing a great job!! i’m very gratefull!

regard, groeten

Jan

**Comment by webfashionist** [comment]
Using the editor in a separate window isn't very user-friendly, as popups shouldn't be used anymore (beside inside-DOM popups, with DIV containers for example - but in this case the parent height of the popup will define the height of the editor, if `heightPercentage` is set, otherwise the `height` option can define a fixed height of the editor).

To your second suggestion: I've now added the possibility with the options `id` and `class` to add custom IDs and custom classes to the outer DIV container of the editor (which currently has the class `richText`). The default class `richText` will not be removed, but simply extended by the custom classes. So now it is possible to use separated CSS styles for both (or more) editors on one page, by simply using their custom selectors.

**Comment by Pruus** [comment]
Many thanks, and this is very clever.
