### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by AngeleNault** [webfashionist/RichText#21]
All text is defaulting with a right alignment. I can't see any way of being able to set left as a default?

**Comment by webfashionist** [comment]
There's no setting for any default text alignment - the default is being used from the browser (left alignment) or from any other CSS settings of the website.

So I guess there's another issue in your code.

You should be able to see the editor with it's default settings in the demo of [htmlpreview.github.io](https://htmlpreview.github.io/?https://github.com/webfashionist/RichText/blob/master/examples/index.html).

**Comment by AngeleNault** [comment]
When the richText is removed the texts floats left as intended. Even when wrapping it in an element with a hard coded style, it is overwritten and aligns right. My code is fine.

**Comment by webfashionist** [comment]
Do you have the same issue in the demo?

Keep in mind, that the `<textarea>` field is being replaced through a `<div>` container, so it is possible, that the text alignment is different when you remove RichText without being RichText the cause of it.
