### ISSUE TITLE
Un-set textarea.richtext()

### ISSUE THREAD

**Issue by teneketo** [webfashionist/RichText#22]
I don't seam to be able to find a way to do the exact opposite of what **.richText()** does.
Revert the enriched textarea to it's old boring simple html text area.

**Comment by webfashionist** [comment]
There was no such function implemented previously.

With the currently latest commit, this is now possible:
Having your initial textarea with the class `.content`, after having `.richText()` initialized, you now have the possibility to call `.unRichText()` on the exact same element:

```javascript
$('.content').richText();
$('.content').unRichText();
```

You can as well delay `.unRichText()` by setting the `delay` option to a given amount of milliseconds:

```javascript
$('.content').unRichText({delay: 2000});
```

Does this solve your issue?


_To get the latest changes, please fork, clone or download the repository - this update is not yet in the latest release._

**Comment by teneketo** [comment]
Thanks! It seems to be doing exactly what is advertised, though in my specific case I'm using a div.richText, so I can have it display HTML, before you can click a button to edit said HTML, it should be easy enough for me to adjust it to my specific case.

Again, nice one!
