### ISSUE TITLE
A few suggestions for better user-experience

### ISSUE THREAD

**Issue by Phantomrider** [webfashionist/RichText#24]
Those are not bugs but suggestions! :)

When using RichText with large amount of text in it becomes kinda difficult to navigate through the editor, for lets say - format every heading differently or apply new style to several paragraphs across the whole text.
Is there a way to make user-experience better? Maybe like auto-expanding function so you don't get a scrollbar and maybe the toolbar to become sticky when you have scrolled down (and it's not in the viewport). I noticed with other plugins similar types of behaviour and it makes formatting much easier. The sticky toolbar will be perfect for mobile formatting too!

**Comment by webfashionist** [comment]
Hello,

thank you for your interest in RichText and your suggestions. Sadly I did not have time earlier to actually implement those changes.

The toolbar is now sticky by default and the adaptive height based on the content is configurable with the `adaptiveHeight` setting which works well with the existing `height` and `heightPercentage` settings. Have a look at the options in the [README](https://github.com/webfashionist/RichText#options) to see which values are allowed.

This is not (yet) released as a new version. If you still need this change within your installation, consider using the code from the `master` branch.
