### ISSUE TITLE
Formatter not working properly when using ctrl + a

### ISSUE THREAD

**Issue by Phantomrider** [webfashionist/RichText#25]
When I try to remove a formatting style from the whole text in RichText - it does not remove all of it, or at some parts - not removing anything at all. I noticed it, because the text I'm formatting has black color added to it, but the formatter tool doesn't remove it.
When selecting the whole text with the mouse is working btw, just when using ctrl + a shortkey.

**Comment by webfashionist** [comment]
Thank you for your feedback.
The editor needs to be focused before using `CTRL + A`, so clicking inside the editor, then using the shortkey should do the thing.

**Comment by Phantomrider** [comment]
It is focused on the editor. I'm placing the cursor somewhere in the paragrapth and then use the CTRL + A shortkey for selecting the whole thing. Then when I use the formatting tool - it does not remove the coloring of the text.

**Comment by webfashionist** [comment]
Are you using the latest release and tested on the demo version available on the README page?
How is the font color set? Through the `style` attribute or through the `font` tag with the `color` attribute?

**Comment by webfashionist** [comment]
I've updated the code to replace `<a>` tags when using the formatter.

Which browser are you using when having issues with selecting the text with your keyboard?

**Comment by Phantomrider** [comment]
My main browser is Firefox.
Btw, I noticed another strange behavior - when selecting parts of symbols and you try to select a word, which is in bracket, it looses the entire selected text once you reach the opening bracket & the editor looses its focus.

**Comment by webfashionist** [comment]
I didn't figure out the issue with `CTRL+A` on Firefox yet, but if you select the text with the keyboard it shouldn't anymore cut off one letter with the latest commit.

I couldn't reproduce your issue with the brackets, can you give me an example where the issue occurred?

**Comment by Phantomrider** [comment]
It's strange, but now when I edit saved text I do not have this issue. I will continue to use it and try to detect when exactly is doing it.
