### ISSUE TITLE
useParagraph: true not working in FF

### ISSUE THREAD

**Issue by Phantomrider** [webfashionist/RichText#26]
I set the configuration of my editor to useParagraph: true, but in Firefox 60.0.2 it is still using `<div>` instead of `<p>`

**Comment by webfashionist** [comment]
I tested it with the same Firefox version and it works just fine for me.
This is the code I used to initialize the editor:

```javascript
$('.content').richText({useParagraph: true});
```

**Comment by Phantomrider** [comment]
Okay, so I downloaded once again the editor and tried it out - it does work, but only if the editor is initialised empty. When you try to initialise it with the <br> tag which is always added - it does not work properly. Testing it with the lastest version, FF 61.0.1

**Comment by webfashionist** [comment]
Which tag do you mean?

**Comment by Phantomrider** [comment]
The default `<br>` tag which is added if editor is empty

**Comment by webfashionist** [comment]
If you initialise the editor with `<div>` tags, the browser (by default) continues to use these tags, no matter which settings are used in the editor.

With the latest commit, predefined tags will be replaced by the tags defined through the settings.
So if you are using `<div>` tags in your code and using `useParagraph: true`, these `<div>` tags will be replaced through `<p>` tags.
