### ISSUE TITLE
How do I bind the data and read it for input and output?

### ISSUE THREAD

**Issue by Jacksonong2011** [webfashionist/RichText#29]
Hi there,

Any idea how we can bind and output the data? I have been trying for few weeks, but can't seems to be able to do it.
Thanks if anyone knows the answer.

![image](https://user-images.githubusercontent.com/40136666/42750106-8da30444-8918-11e8-9b57-2cb25afe7701.png)

**Comment by webfashionist** [comment]
What are you trying to do? Do you want to output saved HTML code to the editor?

Simply output the value in your initial `textarea` and it will automatically be copied to the editor itself.

Like so:

```html
<textarea class="content"><div>Some Text</div></textarea>

<script>
    $(document).ready(function() {
        $('.content').richText();
    });
</script>
```

The code `<div>Some Text</div>` will then be used inside the editor.

**Comment by Jacksonong2011** [comment]
Hi, yes I am calling using .richtext() to render the div. The screenshot above was capture with developer tool. 

My thing is I need to bind my data to the editor and read back the data to save in my database. I am using jQuery to bind the data, but nothing seems to appear and even when I try to read back, it seems there is no data, I may be using it wrongly. Do u have any sample code on binding and reading the data?

Many thanks for ur help and advice.

**Comment by webfashionist** [comment]
You only need to work with your initial `<textarea>` field. So using `$('.content').val()` to read and `$('.content').val('Some text')` to set the value works just fine. 
There's no need to work with `data-` attributes.

However, if you set the value dynamically through jQuery, you should call `.richText()` only after the value has been set to the textarea field.

**Comment by Jacksonong2011** [comment]
Thanks Bob. You are a wonder. Just a small piece of advice and it is working now. :)
