### ISSUE TITLE
Issue when using title option

### ISSUE THREAD

**Issue by pgyordanov** [webfashionist/RichText#31]
I am using the text editor for an article creation functionality. There are multiple languages, so there must be an instance of the text editor for each one. I initially thought that the multiple editors on a single page were the cause, but I tried with only a single editor and the problem persists. It is the following:
When I use the title option more than 2 or 3 times the content editor element disappears. The toolbars and content remain, but this element `<div class="richText-editor" id="richText-xjr0bk" contenteditable="true">{content here}</div>` disappears from the page. Also I noted that in the demo page when I use the heading option it changes the current content, but when I use it on my site it duplicates the content. I attached a screenshot of the issue.

This is the code I use to initialize the richtext editors. And my textearea element doesn't have additional events attached that might mess with the plugin.
`$('.richtext').each(function () {
                var id = $(this).attr('id');

                $(this).richText({
                    // uploads
                    imageUpload: false,
                    fileUpload: false,
                    // link
                    urls: true,
                    //media
                    videoEmbed: false,
                    // translations
                    // dev settings
                    useSingleQuotes: false,
                    id: "richtext-" + id,
                    useParagraph: false
                });
            });`
![issue](https://user-images.githubusercontent.com/10290116/44666405-0176b680-aa21-11e8-80cb-91e57eb3334a.PNG)

**Comment by webfashionist** [comment]
Can you please post the RichText version (from the `info.json` file) and the browser and browser version you're using?

What exactly do you mean by "it changes the current content"? Does it change the selection to the selected title as intended or does it change the content in another way?

**Comment by webfashionist** [comment]
I've tried to reproduce your issue, with Firefox 61.0.2, the latest RichText version and your RichText settings, but I don't get the same result...

If your cache is cleared and you still have the same issues, then some other JavaScript code might produce that bug - as even the demo works as expected for you. Where exactly does `$(this)` come from? There seems to be more code around the actual editor.

**Comment by pgyordanov** [comment]
```
 $('.richtext').each(function () {
                var id = $(this).attr('id');

                $(this).richText({
                    // uploads
                    imageUpload: false,
                    fileUpload: false,
                    // link
                    urls: true,
                    //media
                    videoEmbed: false,
                    // translations
                    // dev settings
                    useSingleQuotes: false,
                    id: "richtext-" + id,
                    useParagraph: false
                });
            });
```
This is the whole code. I just iterate all textareas. Yes, there is other JS running on the page, but none of it directly interects with the richtext editor.

**Comment by pgyordanov** [comment]
I disabled all scripts on the page except jquery and the richtext and still the issue remains

**Comment by webfashionist** [comment]
Does it work for you, if you run the examples from this repository (with and without your RichText settings) on your local or remote environment?

**Comment by pgyordanov** [comment]
I tested and can confirm that the issue is present on a app only using two scripts - jquery 1.12.4 and the editor JS
Below is the whole markup of the page, along with the code used to initialize. Again tested on Firefox 61.0.2

`<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>richtext test</title>
    <link rel="stylesheet" href="richtext.min.css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
</head>
<body>
<div>
<textarea class="richtext"></textarea>
</div>
<script
			  src="https://code.jquery.com/jquery-1.12.4.min.js"
			  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
			  crossorigin="anonymous"></script>
<script src="jquery.richtext.min.js"></script>
<script>
	$(document).ready(function(){
		$('.richtext').richText();
		});
</script>
</body>
</html>`

**Comment by webfashionist** [comment]
I've tested your code and even though I don't get exactly your error, I do get a very similar one.
The issue there is the jQuery version, you should consider updating to jQuery 3 (jQuery 3.2.1 is being used in the demo pages).

Even though you probably will loose support for older browsers (like very old ones: Internet Explorer 6-8, Opera 12.1x or Safari 5.1+), this is the only way you'll get the latest standards for new jQuery plugins.

**Comment by pgyordanov** [comment]
Thank you for your time. This does the trick. I will be closing the issue now.
