### ISSUE TITLE
Selection isn't being saved properly on focus loss.

### ISSUE THREAD

**Issue by vlatri** [webfashionist/RichText#32]
I've created a custom form to upload local files, and every time a user tries to use it, the link to the uploaded file gets put at the very beginning of an article user is currently writing. The actual cursor position at the moment when editor loses focus doesn't matter at all. It gets overriden with {start: 0, end: 0} by saveSelection() in case of a simple caret. But, if I actually select some text, it's position is saved just fine, and the link is placed right where it has to be.

**Comment by vlatri** [comment]
Also, could you please let me know what exatly `anchor !== false` on lines 1181 and 1182 is supposed to mean? Changing it to `anchor === false` seems to fix the issue.

**Comment by webfashionist** [comment]
Which browser are you testing it on?
I've tested with Chrome and Firefox, with both browsers I can add the image where my cursor previously was within the editor.
