### ISSUE TITLE
Attribute required not working

### ISSUE THREAD

**Issue by taikoiv** [webfashionist/RichText#33]
I've used a textarea to initialize RichText plugin using reachText(). Textarea had the attribute required but when i submit the form it doesn't check it.

**Comment by webfashionist** [comment]
Hi!

The `required` attribute is not being removed from the `textarea`. The only thing is, is that the `textarea` field is being hidden if you are using the editor which might result in it being ignored for any form validations. If you are using a library like jQuery Validate, you'll need to remove the field from the ignored list, which includes by default all the hidden fields.
