### ISSUE TITLE
Any chance to change <p> to <br> ?

### ISSUE THREAD

**Issue by suzsuzuki** [webfashionist/RichText#34]
Any chance to change `<p>` to `<br>` ?I tried to manage the code but no luck

**Comment by webfashionist** [comment]
Depending on the browser you are using either `<p>` or `<div>` tags will be created by default.
Usually, with the latest browser versions it is more likely to be a `<div>` container, but the setting `useParagraph` needs to be set to `false` for that.

For now `<br>` tags can only be used if you press SHIFT while using ENTER to go to the next line.
