### ISSUE TITLE
Problem when click undo button while having multiple instances of richtext

### ISSUE THREAD

**Issue by sairfan1** [webfashionist/RichText#35]
**Reproducing the issue:**

1. Setup two instance of rich text box on same page
$('.content1').richText();
$('.content2').richText();

2. Change some text in .content1 text box, and then undo those changes
3. All the text inside .content1 has been copied into .content2 
(i also tried by using ids but no luck)

**Comment by webfashionist** [comment]
Thank you for your issue post!

The bug has been reproduced, checked and tested. It should work for you now with the latest [release](https://github.com/webfashionist/RichText/releases).

**Comment by sairfan1** [comment]
Thanks for your help.
