### ISSUE TITLE
Load new content not working

### ISSUE THREAD

**Issue by domxh1973** [webfashionist/RichText#38]
Hey Webfashionist, first of all many thanks for this wonderful plugin.

I'm trying to reuse the plugin on a single page but this doesn't seem to work. The user can click on a list of item and each time (s)he does this I would like to load new content (with jQuery) in the textarea. It seems that once the richText() method has been called this is not possible anymore. I've tried to unRichText(), set the new content of the textarea and richText() again, but this doesn't work. Any suggestions on how I could achieve this?

Thanks a lot and regards,

Domien

**Comment by domxh1973** [comment]
I've solved this by wrapping the textarea with a div and then using jQuery empty() and append() to create a new textarea on the fly. Then applying richText works perfectly. So it's a bit of a workaround, would still be nice though to know how to just change the contents of the textarea.

Regards,

Domien

**Comment by webfashionist** [comment]
hey,

thank you for your feedback.

I didn't test your issue for now, but even if the editor would allow to load new contents "on the fly" while the editor is running on a specific textarea field - it could produce more troubles concerning adding images, tables, formatting the text, undo/redo feature, etc (as the whole content and code has changed).

This change would probably make more difficulties as it would help, so I guess you would have to go the way you are going right now by creating a new textarea on the fly.
