### ISSUE TITLE
maxlength

### ISSUE THREAD

**Issue by FatBirdie** [webfashionist/RichText#39]
Hi

First off, great script, many thanks for a great job!

I've encountered an issue when trying to limit input length to textarea.
Trying to check maxlength=INT with $('textarea[maxlength]').keyup(function(){ it does not work with richtext as it seems div with "richText-editor" class takes over. Could we see an update where the "richText-editor" div inherit the set values such as maxlength from a textarea (if my assessment is correct regarding the problem) ?

Cheers !!

**Comment by webfashionist** [comment]
Hi,

Thank you for your feedback. 

However, I don't really understand the use-case of this feature as you would limit the HTML code and not the actual text within the textarea element. And limiting the HTML code would result in layout issues as closing tags could be cut off if the limit of `maxlength` is reached.

**Comment by FatBirdie** [comment]
Hi webfashionist 
Use case would be to assign a parameter to limit the number of chars. The HTML code needs to be stored somewhere, and in many cases you wouldn't want to use blob or text i sql for example. In a community driven website you may be would want to limit the chars to a few thousand per user, but I still see your point in regards that HTML might end up broken due to it. Tricky.

**Comment by webfashionist** [comment]
I guess the latest commit could help you out. 
However, it only considers the length of the text, not of the HTML code around it.

**Comment by FatBirdie** [comment]
Absolutely lovely webfashionist, works like a charm ! A big thanks to you !
Its really no problem if it only works on raw text. Leaving a 5k char buffer for HTML in SQL is better than no limitations what so ever.

Great work!!
