### ISSUE TITLE
Font selector

### ISSUE THREAD

**Issue by AmFearLiath** [webfashionist/RichText#4]
Is it possible to implement an additional button, to change the font name?

**Comment by webfashionist** [comment]
Sure it is possible. I've added it now c26d4fb .
You can enable/disable the font button and set your own font list, if needed with the `fontList` option. 

I had not implemented it until now, as usually the content container should be styled with external CSS and not inline formatting. However, for completeness of the editor, it is now possible.

The default font list is based on the fonts which should be available on every main operating system. Any other additional font might not work on every operating system, so you may need to add the font to your website manually (e.g. with Google Fonts) and update the `fontList` option accordingly.

---

*This update is not yet in the [releases](https://github.com/webfashionist/RichText/releases) list, if you need to download it, please do so by downloading it using the `Clone or download` button on the repository page.*

If you want to know more about the available options and their default values, please see the [README](https://github.com/webfashionist/RichText#options) file.

**Comment by AmFearLiath** [comment]
wow this was fast, i'll test this soon
