### ISSUE TITLE
Remove toolbar margin and padding

### ISSUE THREAD

**Issue by etlel** [webfashionist/RichText#41]
Make sure to remove margin and padding from `.richText-toolbar > ul`. Result in Bootstrap 4.3.1 is like this:

![Capture du 2019-04-21 12-38-52](https://user-images.githubusercontent.com/17115179/56472988-55f8f700-6433-11e9-96bf-770966ed6758.png)

**Comment by webfashionist** [comment]
I've added the modifications to the master branch, it should work now for you.
