### ISSUE TITLE
Same text is coming for while having multiple instances

### ISSUE THREAD

**Issue by grandhegopal** [webfashionist/RichText#42]
I have two more than one content boxs on the same page, if i type anything in first content box same text is copied to remaining content boxs, even i am using ids for each box but no luck.

Can you plse advise.

![image](https://user-images.githubusercontent.com/8876114/56738413-2f67f280-678a-11e9-8e52-b336b3aeb0c5.png)

**Comment by webfashionist** [comment]
How did you initialize both editors?
