### ISSUE TITLE
Clicking on richText is not working from scripts

### ISSUE THREAD

**Issue by StruninIhor** [webfashionist/RichText#43]
I'm trying to focus on richtext editor area using jquery.click and jquery.docus functions using all selectors, possibly related to richtext. But nothing works. I added window.bind('click' ... function to catch all e events when something is clicked, I was trying to click on my div tag, which have to be focused, cursor appeared, and all works fine. But when I use jquery.click function, bubbled events are same, but no cursor appeared. How can I focus on richText using jquery?

**Comment by webfashionist** [comment]
You can focus it like this:

```
$('.richText-editor').focus();
```

Of course, if you have multiple editors on one page, you'll need to select the right one through a more precise CSS selector.

**Comment by webfashionist** [comment]
The editor can as well only be focused after it has been loaded through the `.richText()` method.

**Comment by StruninIhor** [comment]
I have found a solution(this is for only one editor on page):
```
setTimeout(() => {
$('div[contenteditable=true]').focus();
}, 0)

``
