### ISSUE TITLE
Code view replacing manually input <div> and <p> tags or vice versa if useParagraph is true

### ISSUE THREAD

**Issue by pgyordanov** [webfashionist/RichText#46]
I'm running the plugin with jQuery 3.4.1. The issue is that `<p>` is being replaced with `<div>` when being manually input in code view (or `<div>` being replaced with `<p>` when useParagraph is true). The issue is there regardless of browser vendor and version. I understand there is a default tag used in the default view, but why is manually input HTML being replaced as well. Can this be corrected?

**Comment by webfashionist** [comment]
Allowing a mixture of both `<p>` and `<div>` tags adds an additional issue:
If you are working within the editor (not in the code view), by entering new lines it would either add a new `<p>` or a new `<div>` depending on the tag surrounded by the caret.
So you would never really know which tag will be created if you enter new lines.

If you still want to try it out or use it for your project, you can search the `fixFirstLine()` function and remove the `else` clause.

**Comment by pgyordanov** [comment]
I see, thank you for the explanation. In my project it's not an issue as code view is what is mostly used. Removing the `else` clause worked.
