### ISSUE TITLE
is there a feature to disable?,  so that users cannot do text editing

### ISSUE THREAD

**Issue by galihprasetio** [webfashionist/RichText#49]
### Feature request checklist

- [x] This is a single feature (i.e. not a re-write of all of RichText)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (e.g.: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/webfashionist/RichText/issues) and to the best of my knowledge this is not a duplicate

**Comment by RaphaelQuem** [comment]
@webfashionist isn't this already achievable through 

`$('.richText-editor').prop('contenteditable', false);`

Just commenting so it might close the issue and help others with this problem.

**Comment by webfashionist** [comment]
A new setting named `preview` has been added. 
If set to `true` it will not load the toolbar buttons and prevent the HTML container to be editable.

This is not (yet) released as a new version. If you still need this change within your installation, consider using the code from the `master` branch.
