### ISSUE TITLE
On adding a new URL,the url is displayed inside the url dropdown instead of the content editable area

### ISSUE THREAD

**Issue by rahulpoochi** [webfashionist/RichText#51]
![issuetextarea](https://user-images.githubusercontent.com/54894808/64254479-1f80cc00-cf3d-11e9-9110-0866e8c2177d.PNG)

**Comment by rahulpoochi** [comment]
This issue happens to me when iam using this plugin in Microsoft Edge.it occurs in times for chrome too..

**Comment by webfashionist** [comment]
Hello,

thank you for your issue report and sorry for the late response. I have now implemented a fix which should be fixing your issue too. If you still encounter this issue do not hesitate to re-open this issue or create a new issue.


This is not (yet) released as a new version. If you still need this change within your installation, consider using the code from the `master` branch.
