### ISSUE TITLE
cant'n change de value with JS

### ISSUE THREAD

**Issue by elVengador** [webfashionist/RichText#52]
when I try to set text into the RichText with Js, it does'n work
![Captura de pantalla (76)](https://user-images.githubusercontent.com/27080940/64809429-e2c95c00-d55e-11e9-9a06-3791407d8424.png)

**Comment by hgd60** [comment]
It's the same in my project. 

1. Deactivating ".richText()", all works fine. Content is saved in the database and restored in the textarea. 
2. Using ".richText()", RichText works as expected and the content ist saved in the database as a kind of HTML-Code (see below), but not restored by "$("#mlebeschreibung").val(obj.beschreibung);". 

I also tried with fix text "$("#mlebeschreibung").val('Hallo');" -> doesn't work

Is there any idea, to solve the problem?

---code in the database---
&lt;div align=&quot;left&quot;&gt;Eingabetext ohne Formatierung&lt;/div&gt;&lt;div align=&quot;left&quot;&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Neue Zeile&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;Fettdruck&lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;&lt;br&gt;&lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;i&gt;Kursiv&lt;/i&gt;&lt;/div&gt;&lt;div&gt;&lt;i&gt;&lt;br&gt;&lt;/i&gt;&lt;/div&gt;&lt;div align=&quot;right&quot;&gt;Rechtsbündig&lt;/div&gt;&lt;div align=&quot;right&quot;&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Zentriert&lt;/div&gt;&lt;div&gt;&lt;i&gt;&lt;br&gt;&lt;/i&gt;&lt;/div&gt;&lt;div&gt;&lt;i&gt;&lt;br&gt;&lt;/i&gt;&lt;/div&gt;&lt;div&gt;&lt;i&gt;&lt;br&gt;&lt;/i&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;
---

**Comment by hgd60** [comment]
additional mark: brackets in the database are coded as & l t ; and & g t ;

**Comment by webfashionist** [comment]
@elVengador @hgd60 
Using (for example) `class="content"` on your `textarea` you can do the following to update the value within RichText:

```
$('.content').val('Some text').trigger('change');
```

Notice the `.trigger('change')` which is required in order to make it work.

**Comment by webfashionist** [comment]
@hgd60 
The way the brackets are saved in the database is caused by your backend code, not by RichText.

**Comment by hgd60** [comment]
great, it works!
thank you very much.
