### ISSUE TITLE
More a question than a request

### ISSUE THREAD

**Issue by domxh1973** [webfashionist/RichText#54]
Hello Webfashionist,

I'm using your RichText component and very happy with it. However, I'm trying to do something which I'm not exactly sure how to. I want my user to be able to insert a hyperlink, but instead of having him/her typing the exact url, I would like to be able to open a div-element into which i will provide an overview of their documents. When they click on the document I would the automatically fill in  the url-field of your widget. I've got no idea if this is possible at all. 

A workaround i've been trying, but which doesn't work yet, would be to provide a button outside of your widget, getting the exact document url and then injecting it inside the RichText editor.

I'm sorry that this is more of a question than an issue report.

Regards,

Domien Holthof

**Comment by webfashionist** [comment]
Hey Domien,

have a look at the `fileHTML` option which may do what you have in mind.
It allows you to add a dropdown element including the list of documents.

The README explains how you can implement it.

**Comment by domxh1973** [comment]
Hello Bob,

I've solved it in another way. I've added a jquery event handler for the url textbox focus event. This handler shows my document selector, which is too complex to simply put in the fileHTML. This one finally puts the correct url in de url textbox.

Regards,

Domien
