### ISSUE TITLE
For multiple instances of textarea, getting same text .

### ISSUE THREAD

**Issue by nikhilggit** [webfashionist/RichText#55]
I am having multiple text areas to be generated dynamically in a popup.
When I save the data, close popup and open that popup again, it shows same text which is there in first textarea.
I have given ".content" class to textarea and calling it like this 
`$('.content').richText();`
How to resolve this issue.??

**Comment by webfashionist** [comment]
You aren't using "multiple instances" as the `textarea` seems to be the exact same `<textarea>` node in the DOM and using `.richText()` on it doesn't reset the value.

Either you'll have to change the `textarea` value when opening the popup, like so:
```javascript
$('.content').val('Some text').trigger('change');
```

Or you will have to remove the editor and textarea and reload it again (by recreating the nodes through jQuery, for example).
