### ISSUE TITLE
How can RichText be incorporated into a GPLv3+ software ?

### ISSUE THREAD

**Issue by bstarynk** [webfashionist/RichText#58]
Sorry, I am not a lawyer (but living and working in France; and very careful about licensing issues since a free software enthusiast).

I am developing professionally [Bismon](http://github.com/bstarynk/bismon). That code is GPLv3+ licensed and copyrighted by my employer [CEA](https://www-list.cea.fr), and funded by the European Commission thru two H2020 projects.

For technical details about Bismon read [this draft report](
http://starynkevitch.net/Basile/bismon-chariot-doc.pdf) (draft of a future H2020 deliverable).

Bismon is also a web server using [libonion](http://www.coralbits.com/libonion). I would like to copy the `src/jquery.richtext.js` file into Bismon's [webroot/](https://github.com/bstarynk/bismon/tree/master/webroot) directory. Since your [`src/jquery.richtext.js` file](https://github.com/webfashionist/RichText/blob/master/src/jquery.richtext.js) has no copyright notice (as the [AGPL](https://www.gnu.org/licenses/agpl-3.0.html) license requires) I feel unauthorized to do so.

I am doing this professionally as I was warned (internally) to be very careful about free software licenses.

I would appreciate a reply by email to *removed* regarding this topic.
I suggest adding a proper AGPLv3+ copyright notice in every source file.

Respectful regards and Happy new 2020 year.

**Comment by webfashionist** [comment]
Hey,

I’m contacting you as you wrote me about my RichText editor and your licensing issue. 

First off, thank you for using my editor and I’m happy that it may help you with the project you are building.

The easiest way to use licensed open source code would be to use the whole repository in your project. You could fork my repository or directly clone it by using git. Doing it this way would not only directly include the LICENSE file (with all the information about the license being used), but it would also give you the option to keep the editor up-to-date through git. 

If you don’t want to go that way, I’d recommend creating a specified folder for the editor which will include the JS and CSS files, plus the LICENSE file. 

The issue of writing the license information directly within the code, would be, that comments are usually removed when minifiying code and the file size would be larger. And as we both probably know, files used for websites should generally be as small as possible.



If you have further questions, don’t hesitate to write me.


Happy new year to you as well!


Regards,

Bob Schockweiler
webFashion - https://webfashion.eu




Authorisation 10090235/0

**Comment by bstarynk** [comment]
Bismon is a special web server. In practice it has at most a few people using it. Actually, it might happen that only two persons would use it. It could even happen that it won't be used at all (it is a research project, and most projects fails).

I would deeply appreciate continuing that conversation by email.

**Comment by bstarynk** [comment]
I tried to send an email to `hello@webfashion.eu` but it bounced.

**Comment by webfashionist** [comment]
I've already written an email to your email address

**Comment by bstarynk** [comment]
My email reply failed.


<bob.schokweiler@webfashion.eu>: host w00985d6.kasserver.com[85.13.131.74]
    said: 550-5.7.1 Service unavailable; client [217.70.178.242] blocked using
    mail.badip.de 550 5.7.1 please see https://kasserver.com/rbl/ (in reply to
    RCPT TO command)
