### ISSUE TITLE
how to shield the css

### ISSUE THREAD

**Issue by niloufarzahiri92** [webfashionist/RichText#59]
Hello,I use the richtext plugin to view some emails(which I do the html of that and put in our database) and also possible to edit that emails, but once I open a emails, the style of page breaks, do you know how can I shield the html from conflict

**Comment by webfashionist** [comment]
This is not linked to the editor itsef, but to the CSS and formatting of the email. 
You'd have to remove `style` attributes from the HTML nodes and the `style` tag itself to remove conflicts and this should be done in the backend, not through the frontend.

**Comment by niloufarzahiri92** [comment]
thanks for your prompt response, but I want to know is there any solution to use iframe or name-spacing to overcome this problem?

**Comment by webfashionist** [comment]
You can sandbox the email within an iframe, yes. 
You could as well display the editor within an iframe, but the email itself can break the editor too as the editor doesn't use iframes to display the HTML content. 

The editor won't be able to format any iframe content, as this is blocked by your browser for security reasons.
