### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by hectorqlucero** [webfashionist/RichText#60]
### Describe the problem you'd like to see solved or additional feature for RichText
Can you add a placeholder
 
Integrate to a form textarea

### Is there an existing part of RichText this feature is related to or is it something new?
I don't see the placeholder option anywhere.

### Why would other RichText users care about this?
Usually you want to give the users some minimal instructions using a placeholder.

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend this feature to be done?
10

### Feature request checklist

- [x ] This is a single feature (i.e. not a re-write of all of RichText)
- [ ] The title starts with "Feature request: " and is followed by a clear feature name (e.g.: `Feature request: moar cowbell`)
- [x ] I have [searched for existing issues](https://github.com/webfashionist/RichText/issues) and to the best of my knowledge this is not a duplicate

**Comment by webfashionist** [comment]
Hello,

thank you for your enhancement request. The `placeholder` setting has now been added and is documented in the [README](https://github.com/webfashionist/RichText#options).


This is not (yet) released as a new version. If you still need this change within your installation, consider using the code from the `master` branch.
