### ISSUE TITLE
 Please fix the bug.

### ISSUE THREAD

**Issue by twenty20ty** [webfashionist/RichText#62]
### Describe the problem

Nice to meet you, I'm Kenta.

First of all, I'm not familiar with English, so I apologize that English may be wrong.

I'm currently using "Minimal Rich Text Editor With jQuery And FontAwesome-RichText".
There I found a bug.

Please check the verification video by clicking the URL below.
"_[external link removed]_"

In the video above
The area outside the dragged range is also listed.

If you do not select the first character of the line, only the dragged line will be listed.
Please correct so that even if you select the first character of the line, only the selected range will be a list.

When you add a character link in a table tag for the same reason
If you drag everything, it will be thrown out of the <td> tag.
Please click the URL below to check the verification video.
_[external link removed]_

I am very in trouble. Can you please correct the above two points?

### What version and browser are you using?
Version 3 chrome Latest

**Comment by webfashionist** [comment]
Hello,

thank you for your feedback. 
I'm sorry that I don't really seem to understand what you mean or try to describe. Probably a bug regarding the selection?

I won't click on the links you provided for my own security as I don't know the domain and the content provided behind the given URL. Please upload description videos to YouTube, Vimeo, Dailymotion or provide screenshots uploaded directly within this thread.

**Comment by twenty20ty** [comment]
Hello,

Thank you for returning the email

Yes Selection bug.
It happens when a character is dragged and the button is pressed.

I re-uploaded to YouTube.
please confirm.

First URL
https://youtu.be/CCCD4BpYX6M
*I want you not to include test1 in the range when you select test2~test4 in the video.

Second URL
https://youtu.be/b9AIM9EqWk8
*We believe that the phenomenon of Second URL is the same cause as the phenomenon of First URL.

Thank you.

**Comment by webfashionist** [comment]
Thank you for your re-upload. 

There seems to be a selection conversion issue between the HTML view and the code behind it. 
I will fix it as soon as possible

**Comment by twenty20ty** [comment]
Can you do it in the near future? If you have a plan, please tell us your approximate plan

**Comment by webfashionist** [comment]
Hello,

a few selection issues have been fixed since. However, I am unsure if those fixes have an impact on your issue mentionned here. 
Please use the latest code from the `master` branch as the latest changes have not been added to a release just yet.

As both of the YouTube uploads have been removed I consider the issue not relevant as of now.

Please re-open this issue or create a new one if the bug still persists.
