### ISSUE TITLE
Multiple RichText boxes when clicking on the code sign

### ISSUE THREAD

**Issue by mdorf** [webfashionist/RichText#64]
When clicking on the </> sign, the RichText goes into the code mode, but as soon as I focus anywhere inside the box in the code mode, instead of editing, RichText creates a new RichText box within the existing one. I've tried changing the order of imports, but the behavior persists. This is a Rails 5 app. "</>" is the only button that does that, all others appear to work as expected. Thanks for your help on this!

Unfortunately, disabling the code feature is not an option for us, since many of our users would want to paste the raw HTML text directly into the box.

<img width="1019" alt="Screen Shot 2020-09-28 at 8 40 14 AM" src="https://user-images.githubusercontent.com/2042070/94454338-9ef3c580-0166-11eb-879d-bd643dc23701.png">

**Comment by webfashionist** [comment]
Thank you for your report. 

I could not reproduce your issue on my end. 

As I can see from your screenshot, the editor is used within another tool. Did you try reproducing the issue when the editor is used outside of the tool as a "standalone" ? 
There might be additional (external or custom) JavaScript which is triggered as soon as you click on the described button.

**Comment by xandriaNET** [comment]
I can recreate this effect with your delivered example
![image](https://user-images.githubusercontent.com/84378414/118621533-bef3fa00-b7c6-11eb-91ab-ce728c2b6086.png)

**Comment by webfashionist** [comment]
Hello @xandriaNET

in your latest screenshot I can not see any issues which should have occured? 

Can you provide me more information about the browser you are using (name + version) and if you are using plugins which may modify the HTML dom?
