### ISSUE TITLE
Button type is not specified

### ISSUE THREAD

**Issue by SeppJorgen** [webfashionist/RichText#66]
Hello,
on the start I wanna thank you for developing RichText!

There is one problem about buttons in modal for creating tables and links, the button element has no specified type which can lead to jQuery wrongly catch the button for submit form because [If no button type is specified then type "submit" is used.](https://www.w3schools.com/jsref/prop_pushbutton_type.asp)

**Comment by webfashionist** [comment]
Hello,

thank you for your feedback.

With `event.preventDefault()` the `submit` event should have already been prevented. Nevertheless I have now added the button type to clean this up.
