### ISSUE TITLE
Prevent user from using unpermitted options

### ISSUE THREAD

**Issue by jeandav** [webfashionist/RichText#68]
Let's say, if I don't give an option to change the font through the settings, any user can still bypass this by editing the text in another program and copy/pasting it into the RichText editor.

Is there a way to prevent this?

Thanks in advance

**Comment by webfashionist** [comment]
Hey, thank you for your question!

As a `contenteditable` DOM node always allows HTML by default, the editor would always allow formatting by default as well. 
There are two options here:

1. Listen for any paste events in the DOM and clean the HTML code within the editor. This might not be the easiest solution to make it work cross-browser.

2. Or clean up the HTML code when you save the content in the backend. You can simply remove the `<font>` HTML tags from the code. 


The second option would allow to prevent changed fonts alltogether, even if the HTML code has been manipulated in the client/browser.

**Comment by jeandav** [comment]
> Hey, thank you for your question!
> 
> As a `contenteditable` DOM node always allows HTML by default, the editor would always allow formatting by default as well.
> There are two options here:
> 
> 1. Listen for any paste events in the DOM and clean the HTML code within the editor. This might not be the easiest solution to make it work cross-browser.
> 2. Or clean up the HTML code when you save the content in the backend. You can simply remove the `<font>` HTML tags from the code.
> 
> The second option would allow to prevent changed fonts alltogether, even if the HTML code has been manipulated in the client/browser.

Thanks you for your reply! I figured it out using your first suggestion with:

`document.getElementById('nopasting').addEventListener("paste", function(e) {
              e.preventDefault();
              var text = e.clipboardData.getData("text/plain");
              document.execCommand("insertHTML", false, text);
          });`

I'm still new to this but it works! The only thing is that it doesn't keep line breaks, which I would have preferred, but still, it works!
