### ISSUE TITLE
useTabForNext not cycling through richText-btn elements

### ISSUE THREAD

**Issue by nicholasjfowler** [webfashionist/RichText#69]
Hello,

I am currently using the latest version of RichText, and have set the useTabForNext to true when intiliazing the richText area.  I then try to use the tab key to cycle through each of the richText-btn elements (Bold, Italics, Underline, lists, font color, font size, etc).  Does this setting now do this or is there something else I need to do first?  Thanks!

**Comment by webfashionist** [comment]
Hello,

sorry for the late response to this. If the setting `useTabForNext` is enabled, it allows to tab to the next (or previous) RichText instance on the same page if you are using multiple instances of RichText on the same page.

This is not implemented for the toolbar buttons
