### ISSUE TITLE
Selection is not active after switching to code.

### ISSUE THREAD

**Issue by Pruus** [webfashionist/RichText#7]
Is it possible to keep the selected part, in the editor, highlighted when changing to code-mode? This makes editing in codebase faster.

**Comment by webfashionist** [comment]
I will check it.

**Comment by webfashionist** [comment]
I've updated the code now, can you check if it works for you as well?

**Comment by Pruus** [comment]
The basic works. Great, but a little hickup...

Testing result and hickup:
I select a text in normal view, then change to codeview, than back to normalview. The selection is gone and in codeview a strange behaveour. Do, select a part in normal view, than changing the by just toggle between normal and codeview for a few times. Then you see:
The selection in normal view is gone and in codeview it goes a few steps forward. Every time you toggle.

**Comment by webfashionist** [comment]
I've now fixed it. As currently the selection is not monitored on the code view, it will simply put the caret at the end of the text in the editor view.

I hope this helps.

**Comment by Pruus** [comment]
Great and fast work. This works fine! Thanks.
