### ISSUE TITLE
Bug into restoreSelection function

### ISSUE THREAD

**Issue by gtezini** [webfashionist/RichText#72]
Hi,
First of all I would like to thank you very much for the excellent component!

I had an issue trying to insert a [table] inside the richText area, so inspecting the code i could find that the culprit was these lines inside the function called restoreSelection:

![image](https://user-images.githubusercontent.com/22347957/137181658-3a7d7437-b3b0-4813-a69d-7bccabea0c5f.png)

After removing theses lines, everything worked as expected.

regards,
gtezini

**Comment by webfashionist** [comment]
Hello @gtezini

thank you for your feedback.

Can you describe me what exactly the issue of inserting a table was? Did you get an error in the dev console, didn't the table you inserted show up? What exactly happened?

**Comment by webfashionist** [comment]
If you try testing this issue again, please use the latest code from `master`. With the commit cfec793 I have implemented a fix for another issue which may or may not have an impact on your issue as well
