### ISSUE TITLE
change to english

### ISSUE THREAD

**Issue by quantrpeter** [webfashionist/RichText#73]
Hi, how to change the button text to english?

![image](https://user-images.githubusercontent.com/50471577/145434276-a3b75989-a3f2-4c5d-b37d-999f151de8d4.png)

thanks

**Comment by webfashionist** [comment]
Hello @quantrpeter 

have a look at the options in the [README](https://github.com/webfashionist/RichText#options). 

There's a property called `translations` in the constructor which has multiple translation keys set. In this case you are looking for the `add` key in the `translations` object.
