### ISSUE TITLE
Write text area into a database

### ISSUE THREAD

**Issue by RKwasi** [webfashionist/RichText#75]
Seems simple, and I'm doing it with tinyMCE just fine, latest version and older versions too.

Anything special I need to do to have the form write the textarea copy into my db???
Driving me crazy all night long.
Using your sample, just can't get the form to write the textarea copy into my db

grrrrr

**Comment by webfashionist** [comment]
Hello is this still an issue @RKwasi?
If so, the initial textarea works just as any other textarea within your form. Either you submit the form or you select the textarea value with JavaScript to get the current value and save it via Ajax.
