### ISSUE TITLE
Strip unrequired html?

### ISSUE THREAD

**Issue by csjui** [webfashionist/RichText#78]
Is there a way to strip html that results (I think) from copy and pasting into the editor? For example, below:

`<span lang=\"EN-US\" style=\"font-size: 1rem; letter-spacing: 0px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: Calibri, &quot;sans-serif&quot;;\">OK</span><span style=\"font-size: 1rem; letter-spacing: 0px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;\">`

Thank you

**Comment by webfashionist** [comment]
Currently not, you should however be able to paste cleaned text by right clicking in the editor. There should be some kind of option to paste without styling or with adapted style.
