### ISSUE TITLE
More Size Options

### ISSUE THREAD

**Issue by rehanakhalid** [webfashionist/RichText#79]
### Describe the problem you'd like to see solved or additional feature for RichText

There should be more sizes available in the font size dropdown or better yet this should be a setting which can be set/ customized by user same as font family dropdown.
I have actually fixed this issue on my local but I think this should be available by default. I can commit my code to the repository but I wasn't sure of the contribution policy.

### Is there an existing part of RichText this feature is related to or is it something new?

Toolbar - Font Size

### Why would other RichText users care about this?

This is actually a hard requirement of one of our client so I assume other users would also want this.

### Feature request checklist

- [ ] This is a single feature (i.e. not a re-write of all of RichText)
- [ ] The title starts with "Feature request: " and is followed by a clear feature name (e.g.: `Feature request: moar cowbell`)
- [ ] I have [searched for existing issues](https://github.com/webfashionist/RichText/issues) and to the best of my knowledge this is not a duplicate

**Comment by webfashionist** [comment]
Thank you for your request.

Feel free to add a PR for line 346 in the non-minified JS file with a change you would suggest. Otherwise, let me know what your suggestion is so that I can implement it.

**Comment by webfashionist** [comment]
Hi @rehanakhalid 

Additional font-sizes have been added with 22c46c3e8aac591d3bfe847a79d5189ecf2a3242 

Please let me know, if additional font-sizes are needed.
