### ISSUE TITLE
Issue with Hyper link when multiple editors are used

### ISSUE THREAD

**Issue by gatalanaresh** [webfashionist/RichText#8]
Hi
If we are using hyperlink on multiple editor. It is not working as expected.

If we select a part of text in the first editor and choose hyperlink and click ok. The link is added to the start of the editor instead of making the selected text hyperlink.

Thanks,
Naresh

**Comment by webfashionist** [comment]
I've found the issue and updated the editor. It worked fine in Chrome, but I could reproduce it in Firefox.

Please keep me up-to-date if you encounter further issues.

---

*This update is not yet in the [releases](https://github.com/webfashionist/RichText/releases) list, if you need to download it, please do so by downloading it using the `Clone or download` button on the repository page.*

**Comment by gatalanaresh** [comment]
Thank you. It is working as expected on Chrome and Firefox.
