### ISSUE TITLE
Feature request: function to set background color 

### ISSUE THREAD

**Issue by bit-mschwingenschloegl** [webfashionist/RichText#81]
### Describe the problem you'd like to see solved or additional feature for RichText

It would be great to be able to set a background color for the selected text. 

### Is there an existing part of RichText this feature is related to or is it something new?

New function. Similar to function fontColor.

### Why would other RichText users care about this?

Just would be a nice feature.

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend this feature to be done?

10
At the moment I work on an alternative GUI which should cover most existing functions:
![grafik](https://user-images.githubusercontent.com/98806423/181246976-709176aa-b4d7-497f-82eb-d7ee7d620f9f.png)
(It's a pretty individual problem ;) )

### Feature request checklist

- [X] This is a single feature (i.e. not a re-write of all of RichText)
- [X] The title starts with "Feature request: " and is followed by a clear feature name (e.g.: `Feature request: moar cowbell`)
- [X] I have [searched for existing issues](https://github.com/webfashionist/RichText/issues) and to the best of my knowledge this is not a duplicate

**Comment by webfashionist** [comment]
Not really sure if background colors for text is currently even being actively used on modern websites. However, I will keep this feature request on a low prio todo for now as long as no one else requests this

**Comment by webfashionist** [comment]
This has been implemented with [9e878bf](https://github.com/webfashionist/RichText/commit/9e878bfce34c291733beabb4fc7b6b2c5701339b)

**Comment by bit-mschwingenschloegl** [comment]
Thank you very much.
