### ISSUE TITLE
Get html text to upload to a database

### ISSUE THREAD

**Issue by RubenRDC** [webfashionist/RichText#83]
**I wanted to see how to access the text entered in the textarea and then upload it to a database... another thing... can writing scripts and PHP code be blocked in the textarea?**

**Comment by webfashionist** [comment]
Hi @RubenRDC

The RichText field works as any other textarea in your form and can simply be accessed via PHP as the other fields. Not sure how I can assist you without knowing your code base.

Blocking scripts should be done via PHP to actually prevent it from being saved even if Frontend code has been manipulated.

**Comment by RubenRDC** [comment]
I have tried to access the textarea with php through a form by putting an id in the plugin configuration but PHP throws the id I am trying to access null

**Comment by webfashionist** [comment]
PHP does not access any input fields by its ID, but by the `name` attribute.

**Comment by RubenRDC** [comment]
I'm not very familiar with PHP, I was wondering if you could give me an example, anyway the problem I have is that when I put any script in the text area, it runs instantly

**Comment by RubenRDC** [comment]
Hello, would you not give me an example of how to obtain the content of the Richtext and filter it?  please

**Comment by webfashionist** [comment]
The RichText field can simply be used within a `<form>` and submitting it, sends the input value to the backend.
Not having any insights in your code makes it impossible to solve the issues you have and additionally would go way beyond this open source project.

You can however also get access to my freelance web developer services, if you wish so.
