### ISSUE TITLE
Toolbar btn not working 

### ISSUE THREAD

**Issue by wolff777** [webfashionist/RichText#84]
Hi, 
Some toolbar btn's are not loading, no matter if they are configured: 
uploadImage (local)
resizeImage (from the above - so, uploaded image needs to be adjusted inside text field)
uploadFile (local) 
uploadVideo (local) 

Regards, 
wolf

**Comment by webfashionist** [comment]
Hi,

please add more info and code snippets to help to reproduce the error you got.
