### ISSUE TITLE
Listenelemente

### ISSUE THREAD

**Issue by daka02** [webfashionist/RichText#86]
Hallo Bob,

habe folgendes Problem: wenn ich eine Überschrift oder Text eintippe und darunter ein Liste einfüge, werden die Überschrift/der Text autmatisch als Listenelement übernommen. Die Überschrift bwz. der Text über der Liste sollten jedoch ein eigenständige Elemente bleiben. Vlt. gibt es dafür eine Lösung? Vielen Dank im Voraus & LG aus AT

**Comment by webfashionist** [comment]
Hallo Daniel,

Ich vermute ein Fehler bei der Positionierung des HTML Tags und somit bei der erkannten Caret Position. Auf Anhieb habe ich da keinen Fix parat, solltest du jedoch den Fehler finden kannst du gerne ein PR öffnen.

LG

**Comment by webfashionist** [comment]
To give others the opportunity to be included in the issue conversation and keep the conversation in english, this will be moved to the #96 issue.
