### ISSUE TITLE
Maxlength not updating on startup and new feature.

### ISSUE THREAD

**Issue by vsc55** [webfashionist/RichText#87]
Hi,
I don't know if it's a problem or something I'm doing wrong.
I am setting the value of maxlength to 1000 but when loading the page the counter appears as 0/1000, it is not updating the counter.
I have to write something and then it updates.

On the other hand, as I see in the documentation, maxlength does not count the html characters, for the use that I need it would be interesting if it counted the complete number of characters (text and html). Is there any way to do it? If there is not, it would be good to add an option to be able to configure it.

Greetings and thank you.

I have the following code:
HTML:
```html
<textarea id="id1" name="id1" class="form-control">Example</textarea>
```
JS:
```js
$('#id1').richText({
	maxlength: 1000,
});
```

**Comment by vsc55** [comment]
Here a solution that works:
https://github.com/vsc55/RichText/commit/50abc11f37518de4783fd8718f2823db20b5bb31

**Comment by webfashionist** [comment]
Hi @vsc55 

thank you for your issue and PR! I've implemented a fix for the `maxlength` setting on startup and a new setting to include counting HTML characters called `maxlengthIncludeHTML`. 

Commit b35465d146ef2ff594d95a7ce27e752af45d31e8

**Comment by vsc55** [comment]
Hi @webfashionist,
In the implementation you have made a small problem.
The maxlength attribute of the textarea is not taken into account.
For example, if you have the following textarea you don't get the limit of 4096.
`<textarea cols="49" rows="10" maxlength="4096">`

What I propose is the following, see what you think:
```php
var maxlength = settings.maxlength;
if (maxlength == 0 &&  $inputElement.attr("maxlength") != undefined) {
	maxlength = $inputElement.attr("maxlength");
}
if (maxlength > 0) {
	// display max length in editor toolbar
	$editor.data('maxlength', maxlength);
	$editor.children('.richText-toolbar').children('.richText-help').before($('<a />', {
		class: 'richText-length',
		text: '0/' + maxlength
	}));
	updateMaxLength($editor.find('.richText-editor').attr('id'));
}
```
