### ISSUE TITLE
bold, Italic and Under line not working

### ISSUE THREAD

**Issue by hussamdd** [webfashionist/RichText#9]
For multiple rich text the bold, Italic and Under line not working

**Comment by webfashionist** [comment]
Thank you for your report.

The issue is fixed with the commit c3c6548 and is already in the latest release [v.1.0.5](https://github.com/webfashionist/RichText/releases/tag/v.1.0.5)

Please keep me up to date if everything works (or doesn't) for you now

**Comment by Moworks** [comment]
Thanks for fixing this, nice use of the Font Awesome icons

**Comment by webfashionist** [comment]
Thank you, I'm glad you like it :)
