### ISSUE TITLE
Empty text create html

### ISSUE THREAD

**Issue by Buissartt** [webfashionist/RichText#90]
Hi,

Got the rich text area inside a form. When I save my object with no text inside the textarea, some HTML is although generated.
`<div><br></div>`

Is there a way I can override this useless HTML generation ? Because of that I'm not able to verify if my field is empty.

Thank you for the job done so far !

**Comment by webfashionist** [comment]
Hi @Buissartt 

this is the same issue as #12 and won't be fixed. Please check the linked issue in order to get an idea on how to check if your value is actually empty.
