### ISSUE TITLE
Setting Font size disregards/affects font-style (Bold/Italic/Underline)

### ISSUE THREAD

**Issue by Richard-Dufour** [webfashionist/RichText#91]
If you have some text with part of it bold, setting the entire text font size affects the font style, disregards the style.

**Comment by webfashionist** [comment]
Hi, thank you for your issue. 

This may be solved now with [4dc4a67](https://github.com/webfashionist/RichText/commit/4dc4a6715c9a16296a753cfaeb8f81fb2b08694c).
If not, please do not hesitate to reply and provide more information about the bug.
