### ISSUE TITLE
getSelectedText can include toolbar options

### ISSUE THREAD

**Issue by Richard-Dufour** [webfashionist/RichText#92]
If you don't set any text in the editor, and right away pick a font size, you get a NULL in the editor
If you have typed some text in the editor but didn't select anything, then pick a font size, the text you entered in the editor is duplicated.
If you haven't set any text in the editor and select a font size, the toolbar menu option for font size is duplicated. 

This is because getSelectedText includes whatever is selected on screen (including the menu option)

` function getSelectedText() {
            var range;
            if (window.getSelection) {  // all browsers, except IE before version 9
                range = window.getSelection();
                return range.toString() ? range.toString() : range.focusNode.nodeValue;
            } else if (document.selection.createRange) { // Internet Explorer
                range = document.selection.createRange();
                return range.text;
            }
            return false;
        }I`

It needs to ignore toolbar menu options.

**Comment by Richard-Dufour** [comment]
![image](https://user-images.githubusercontent.com/69986125/216690387-de59f0bc-1d75-446c-a1af-4e8d698bf358.png)

**Comment by Richard-Dufour** [comment]
Here's the fix I came up with: 

`  /**
         * Returns the text from the current selection
         * @private
         * @return {string|boolean}
         */
        function getSelectedText() {
            var range;
            
            if (window.getSelection) { // all browsers, except IE before version 9
                const selection = window.getSelection();
                if (!selection.isCollapsed)  //  If the selection is not collapsed, it means that some text is highlighted.
                {  
                  range = window.getSelection();
                  return range.toString() ? range.toString() : range.focusNode.nodeValue;
                }
            } else if (document.selection.createRange) { // Internet Explorer
                range = document.selection.createRange();
                return range.text;
            }
            return false;
        }
`

**Comment by Richard-Dufour** [comment]
Also: 

` /**
         * Format text in editor
         * @param {string} command
         * @param {string|null} option
         * @param {string} editorID
         * @private
         */
        function formatText(command, option, editorID) {
            if (typeof option === "undefined") {
                option = null;
            }
            // restore selection from before clicking on any button
            doRestore(editorID);
            // Temporarily enable designMode so that
            // document.execCommand() will work
            // document.designMode = "ON";
            // Execute the command
            if (command === "heading" && getSelectedText()) {
                // IE workaround
                pasteHTMLAtCaret('<' + option + '>' + getSelectedText() + '</' + option + '>');
            } else if (command === "fontSize" && getSelectedText() && parseInt(option) > 0) {
                var selection = getSelectedText();

                //fix for issue when no text selected
                const myParseIntOption = parseInt(option);
                var menuOption = 'Text ' + myParseIntOption.toString() + 'px';
                //console.log("menuOption: ", menuOption);
                if (selection == menuOption)
                    return; 
                //console.log("parseInt(option): ", parseInt(option));
                //console.log("selection: [", selection + ']');

                selection = (selection + '').replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1' + '<br>' + '$2');
                var html = (settings.useSingleQuotes ? "<span style='font-size:" + option + "px;'>" + selection + "</span>" : '<span style="font-size:' + option + 'px;">' + selection + '</span>');
                pasteHTMLAtCaret(html);
            } else {
                console.log('else');
                document.execCommand(command, false, option);
            }
            // Disable designMode
            // document.designMode = "OFF";
        }`

**Comment by webfashionist** [comment]
@Richard-Dufour can you please try to correctly format the code and preferably open a Pull Request with your recommended changes?
