### ISSUE TITLE
Clear rich text textarea

### ISSUE THREAD

**Issue by aahondema** [webfashionist/RichText#95]
Hi,

I am trying to clear the content of a rich text textarea by using some javascript:

<textarea id="editor" class="form-control richtext" rows="31" spellcheck="true">Some content</textarea>

function clearEditor() {
    document.getElementById('editor').value = '';
}

However, this does not work. Is there a way to clear the textarea using Javascript?

Thanks in advance,
Adrian 
The Netherlands

**Comment by webfashionist** [comment]
Hi @aahondema 

as there is the editor and the textarea field, you'll need both containers to be set to an empty value.
I'd however recommend to set the correct value directly into the `<textarea>` element instead of fiddling around with additional JavaScript to get to that result.

**Comment by aahondema** [comment]
Hi,

Yes, I understand. But based on the option in a select box (which links to various documents) I need to load other documents in the editor. Before I load a new document, I will need to clear the previous one first.

Adrian

**Comment by webfashionist** [comment]
Hi @aahondema

With the latest commit you are able to get, set and clear the content of the editor. Have a look at the Readme in order to see how you can implement it in your code.

Hopefully this helps
