### ISSUE TITLE
Any heading breaks the plugin

### ISSUE THREAD

**Issue by Feltim** [webfashionist/RichText#98]
When giving text a heading with the toolbar or without, any text alteration with the toolbar afterwards breaks the plugin.

![image](https://github.com/webfashionist/RichText/assets/43956302/3bd86bfa-78e3-420b-b8d0-52c19b32617c)

Then no buttons work and you cannot type anymore.

**Comment by webfashionist** [comment]
Hi @Feltim 

I can currently not reproduce that with the state of the `master` branch. Were you using a release version or the current `master` state?

**Comment by Feltim** [comment]
I believe it was latest release version.
I usually get it from "releases (latest)" and v.1.0.16 does seem like the one I remember.

Is it possible to add in your comments inside the js file the version?

**Comment by Feltim** [comment]
![image](https://github.com/webfashionist/RichText/assets/43956302/d47f1f90-39bc-4162-83f8-52d85cc60e88)

**Comment by Feltim** [comment]
I downloaded the master version and I can already see quite an improvement in toolbar behavior. 
I am marking this issue as solved since you implied I should be using the master branch.
